//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ctcModel", "fk_event_file_2", "file_repository", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ctc.CtcPdfProcess.DataAccess.dao.file_repository), "event_file", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ctc.CtcPdfProcess.DataAccess.dao.event_file), true)]
[assembly: EdmRelationshipAttribute("ctcModel", "fk_event_file_1", "events", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ctc.CtcPdfProcess.DataAccess.dao.events), "event_file", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ctc.CtcPdfProcess.DataAccess.dao.event_file), true)]

#endregion

namespace Ctc.CtcPdfProcess.DataAccess.dao
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ctcEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ctcEntities object using the connection string found in the 'ctcEntities' section of the application configuration file.
        /// </summary>
        public ctcEntities() : base("name=ctcEntities", "ctcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ctcEntities object.
        /// </summary>
        public ctcEntities(string connectionString) : base(connectionString, "ctcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ctcEntities object.
        /// </summary>
        public ctcEntities(EntityConnection connection) : base(connection, "ctcEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<event_file> event_file
        {
            get
            {
                if ((_event_file == null))
                {
                    _event_file = base.CreateObjectSet<event_file>("event_file");
                }
                return _event_file;
            }
        }
        private ObjectSet<event_file> _event_file;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<file_repository> file_repository
        {
            get
            {
                if ((_file_repository == null))
                {
                    _file_repository = base.CreateObjectSet<file_repository>("file_repository");
                }
                return _file_repository;
            }
        }
        private ObjectSet<file_repository> _file_repository;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<events> events
        {
            get
            {
                if ((_events == null))
                {
                    _events = base.CreateObjectSet<events>("events");
                }
                return _events;
            }
        }
        private ObjectSet<events> _events;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the event_file EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToevent_file(event_file event_file)
        {
            base.AddObject("event_file", event_file);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the file_repository EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofile_repository(file_repository file_repository)
        {
            base.AddObject("file_repository", file_repository);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToevents(events events)
        {
            base.AddObject("events", events);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ctcModel", Name="event_file")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class event_file : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new event_file object.
        /// </summary>
        /// <param name="event_file_id">Initial value of the event_file_id property.</param>
        /// <param name="event_id">Initial value of the event_id property.</param>
        /// <param name="file_repository_id">Initial value of the file_repository_id property.</param>
        /// <param name="status_flag">Initial value of the status_flag property.</param>
        /// <param name="row_created">Initial value of the row_created property.</param>
        /// <param name="row_updated">Initial value of the row_updated property.</param>
        /// <param name="row_created_by_user_id">Initial value of the row_created_by_user_id property.</param>
        /// <param name="row_updated_by_user_id">Initial value of the row_updated_by_user_id property.</param>
        public static event_file Createevent_file(global::System.Int64 event_file_id, global::System.Int64 event_id, global::System.Int64 file_repository_id, global::System.Int32 status_flag, global::System.DateTime row_created, global::System.DateTime row_updated, global::System.String row_created_by_user_id, global::System.String row_updated_by_user_id)
        {
            event_file event_file = new event_file();
            event_file.event_file_id = event_file_id;
            event_file.event_id = event_id;
            event_file.file_repository_id = file_repository_id;
            event_file.status_flag = status_flag;
            event_file.row_created = row_created;
            event_file.row_updated = row_updated;
            event_file.row_created_by_user_id = row_created_by_user_id;
            event_file.row_updated_by_user_id = row_updated_by_user_id;
            return event_file;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 event_file_id
        {
            get
            {
                return _event_file_id;
            }
            set
            {
                if (_event_file_id != value)
                {
                    Onevent_file_idChanging(value);
                    ReportPropertyChanging("event_file_id");
                    _event_file_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("event_file_id");
                    Onevent_file_idChanged();
                }
            }
        }
        private global::System.Int64 _event_file_id;
        partial void Onevent_file_idChanging(global::System.Int64 value);
        partial void Onevent_file_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 event_id
        {
            get
            {
                return _event_id;
            }
            set
            {
                Onevent_idChanging(value);
                ReportPropertyChanging("event_id");
                _event_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("event_id");
                Onevent_idChanged();
            }
        }
        private global::System.Int64 _event_id;
        partial void Onevent_idChanging(global::System.Int64 value);
        partial void Onevent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 file_repository_id
        {
            get
            {
                return _file_repository_id;
            }
            set
            {
                Onfile_repository_idChanging(value);
                ReportPropertyChanging("file_repository_id");
                _file_repository_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("file_repository_id");
                Onfile_repository_idChanged();
            }
        }
        private global::System.Int64 _file_repository_id;
        partial void Onfile_repository_idChanging(global::System.Int64 value);
        partial void Onfile_repository_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_flag
        {
            get
            {
                return _status_flag;
            }
            set
            {
                Onstatus_flagChanging(value);
                ReportPropertyChanging("status_flag");
                _status_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_flag");
                Onstatus_flagChanged();
            }
        }
        private global::System.Int32 _status_flag;
        partial void Onstatus_flagChanging(global::System.Int32 value);
        partial void Onstatus_flagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime row_created
        {
            get
            {
                return _row_created;
            }
            set
            {
                Onrow_createdChanging(value);
                ReportPropertyChanging("row_created");
                _row_created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("row_created");
                Onrow_createdChanged();
            }
        }
        private global::System.DateTime _row_created;
        partial void Onrow_createdChanging(global::System.DateTime value);
        partial void Onrow_createdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime row_updated
        {
            get
            {
                return _row_updated;
            }
            set
            {
                Onrow_updatedChanging(value);
                ReportPropertyChanging("row_updated");
                _row_updated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("row_updated");
                Onrow_updatedChanged();
            }
        }
        private global::System.DateTime _row_updated;
        partial void Onrow_updatedChanging(global::System.DateTime value);
        partial void Onrow_updatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String row_created_by_user_id
        {
            get
            {
                return _row_created_by_user_id;
            }
            set
            {
                Onrow_created_by_user_idChanging(value);
                ReportPropertyChanging("row_created_by_user_id");
                _row_created_by_user_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("row_created_by_user_id");
                Onrow_created_by_user_idChanged();
            }
        }
        private global::System.String _row_created_by_user_id;
        partial void Onrow_created_by_user_idChanging(global::System.String value);
        partial void Onrow_created_by_user_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String row_updated_by_user_id
        {
            get
            {
                return _row_updated_by_user_id;
            }
            set
            {
                Onrow_updated_by_user_idChanging(value);
                ReportPropertyChanging("row_updated_by_user_id");
                _row_updated_by_user_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("row_updated_by_user_id");
                Onrow_updated_by_user_idChanged();
            }
        }
        private global::System.String _row_updated_by_user_id;
        partial void Onrow_updated_by_user_idChanging(global::System.String value);
        partial void Onrow_updated_by_user_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ctcModel", "fk_event_file_2", "file_repository")]
        public file_repository file_repository
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<file_repository>("ctcModel.fk_event_file_2", "file_repository").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<file_repository>("ctcModel.fk_event_file_2", "file_repository").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<file_repository> file_repositoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<file_repository>("ctcModel.fk_event_file_2", "file_repository");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<file_repository>("ctcModel.fk_event_file_2", "file_repository", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ctcModel", "fk_event_file_1", "events")]
        public events events
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<events>("ctcModel.fk_event_file_1", "events").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<events>("ctcModel.fk_event_file_1", "events").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<events> eventsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<events>("ctcModel.fk_event_file_1", "events");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<events>("ctcModel.fk_event_file_1", "events", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ctcModel", Name="events")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class events : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new events object.
        /// </summary>
        /// <param name="event_id">Initial value of the event_id property.</param>
        /// <param name="event_title">Initial value of the event_title property.</param>
        /// <param name="apr_code">Initial value of the apr_code property.</param>
        /// <param name="date_of_service">Initial value of the date_of_service property.</param>
        /// <param name="host_facility_id">Initial value of the host_facility_id property.</param>
        /// <param name="status_flag">Initial value of the status_flag property.</param>
        /// <param name="row_created">Initial value of the row_created property.</param>
        /// <param name="row_updated">Initial value of the row_updated property.</param>
        /// <param name="row_created_by_user_id">Initial value of the row_created_by_user_id property.</param>
        /// <param name="row_updated_by_user_id">Initial value of the row_updated_by_user_id property.</param>
        public static events Createevents(global::System.Int64 event_id, global::System.String event_title, global::System.String apr_code, global::System.DateTime date_of_service, global::System.Int64 host_facility_id, global::System.Int32 status_flag, global::System.DateTime row_created, global::System.DateTime row_updated, global::System.String row_created_by_user_id, global::System.String row_updated_by_user_id)
        {
            events events = new events();
            events.event_id = event_id;
            events.event_title = event_title;
            events.apr_code = apr_code;
            events.date_of_service = date_of_service;
            events.host_facility_id = host_facility_id;
            events.status_flag = status_flag;
            events.row_created = row_created;
            events.row_updated = row_updated;
            events.row_created_by_user_id = row_created_by_user_id;
            events.row_updated_by_user_id = row_updated_by_user_id;
            return events;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 event_id
        {
            get
            {
                return _event_id;
            }
            set
            {
                if (_event_id != value)
                {
                    Onevent_idChanging(value);
                    ReportPropertyChanging("event_id");
                    _event_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("event_id");
                    Onevent_idChanged();
                }
            }
        }
        private global::System.Int64 _event_id;
        partial void Onevent_idChanging(global::System.Int64 value);
        partial void Onevent_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String event_title
        {
            get
            {
                return _event_title;
            }
            set
            {
                Onevent_titleChanging(value);
                ReportPropertyChanging("event_title");
                _event_title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("event_title");
                Onevent_titleChanged();
            }
        }
        private global::System.String _event_title;
        partial void Onevent_titleChanging(global::System.String value);
        partial void Onevent_titleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apr_code
        {
            get
            {
                return _apr_code;
            }
            set
            {
                Onapr_codeChanging(value);
                ReportPropertyChanging("apr_code");
                _apr_code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apr_code");
                Onapr_codeChanged();
            }
        }
        private global::System.String _apr_code;
        partial void Onapr_codeChanging(global::System.String value);
        partial void Onapr_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_of_service
        {
            get
            {
                return _date_of_service;
            }
            set
            {
                Ondate_of_serviceChanging(value);
                ReportPropertyChanging("date_of_service");
                _date_of_service = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_of_service");
                Ondate_of_serviceChanged();
            }
        }
        private global::System.DateTime _date_of_service;
        partial void Ondate_of_serviceChanging(global::System.DateTime value);
        partial void Ondate_of_serviceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> start_time
        {
            get
            {
                return _start_time;
            }
            set
            {
                Onstart_timeChanging(value);
                ReportPropertyChanging("start_time");
                _start_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_time");
                Onstart_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _start_time;
        partial void Onstart_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onstart_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> end_time
        {
            get
            {
                return _end_time;
            }
            set
            {
                Onend_timeChanging(value);
                ReportPropertyChanging("end_time");
                _end_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_time");
                Onend_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _end_time;
        partial void Onend_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onend_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 host_facility_id
        {
            get
            {
                return _host_facility_id;
            }
            set
            {
                Onhost_facility_idChanging(value);
                ReportPropertyChanging("host_facility_id");
                _host_facility_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("host_facility_id");
                Onhost_facility_idChanged();
            }
        }
        private global::System.Int64 _host_facility_id;
        partial void Onhost_facility_idChanging(global::System.Int64 value);
        partial void Onhost_facility_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String event_comment
        {
            get
            {
                return _event_comment;
            }
            set
            {
                Onevent_commentChanging(value);
                ReportPropertyChanging("event_comment");
                _event_comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("event_comment");
                Onevent_commentChanged();
            }
        }
        private global::System.String _event_comment;
        partial void Onevent_commentChanging(global::System.String value);
        partial void Onevent_commentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_flag
        {
            get
            {
                return _status_flag;
            }
            set
            {
                Onstatus_flagChanging(value);
                ReportPropertyChanging("status_flag");
                _status_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_flag");
                Onstatus_flagChanged();
            }
        }
        private global::System.Int32 _status_flag;
        partial void Onstatus_flagChanging(global::System.Int32 value);
        partial void Onstatus_flagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime row_created
        {
            get
            {
                return _row_created;
            }
            set
            {
                Onrow_createdChanging(value);
                ReportPropertyChanging("row_created");
                _row_created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("row_created");
                Onrow_createdChanged();
            }
        }
        private global::System.DateTime _row_created;
        partial void Onrow_createdChanging(global::System.DateTime value);
        partial void Onrow_createdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime row_updated
        {
            get
            {
                return _row_updated;
            }
            set
            {
                Onrow_updatedChanging(value);
                ReportPropertyChanging("row_updated");
                _row_updated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("row_updated");
                Onrow_updatedChanged();
            }
        }
        private global::System.DateTime _row_updated;
        partial void Onrow_updatedChanging(global::System.DateTime value);
        partial void Onrow_updatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String row_created_by_user_id
        {
            get
            {
                return _row_created_by_user_id;
            }
            set
            {
                Onrow_created_by_user_idChanging(value);
                ReportPropertyChanging("row_created_by_user_id");
                _row_created_by_user_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("row_created_by_user_id");
                Onrow_created_by_user_idChanged();
            }
        }
        private global::System.String _row_created_by_user_id;
        partial void Onrow_created_by_user_idChanging(global::System.String value);
        partial void Onrow_created_by_user_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String row_updated_by_user_id
        {
            get
            {
                return _row_updated_by_user_id;
            }
            set
            {
                Onrow_updated_by_user_idChanging(value);
                ReportPropertyChanging("row_updated_by_user_id");
                _row_updated_by_user_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("row_updated_by_user_id");
                Onrow_updated_by_user_idChanged();
            }
        }
        private global::System.String _row_updated_by_user_id;
        partial void Onrow_updated_by_user_idChanging(global::System.String value);
        partial void Onrow_updated_by_user_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> responsible_entity_id
        {
            get
            {
                return _responsible_entity_id;
            }
            set
            {
                Onresponsible_entity_idChanging(value);
                ReportPropertyChanging("responsible_entity_id");
                _responsible_entity_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("responsible_entity_id");
                Onresponsible_entity_idChanged();
            }
        }
        private Nullable<global::System.Int64> _responsible_entity_id;
        partial void Onresponsible_entity_idChanging(Nullable<global::System.Int64> value);
        partial void Onresponsible_entity_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ctcModel", "fk_event_file_1", "event_file")]
        public EntityCollection<event_file> event_file
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<event_file>("ctcModel.fk_event_file_1", "event_file");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<event_file>("ctcModel.fk_event_file_1", "event_file", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ctcModel", Name="file_repository")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class file_repository : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new file_repository object.
        /// </summary>
        /// <param name="file_repository_id">Initial value of the file_repository_id property.</param>
        /// <param name="file_name">Initial value of the file_name property.</param>
        /// <param name="status_flag">Initial value of the status_flag property.</param>
        /// <param name="row_created">Initial value of the row_created property.</param>
        /// <param name="row_updated">Initial value of the row_updated property.</param>
        /// <param name="row_created_by_user_id">Initial value of the row_created_by_user_id property.</param>
        /// <param name="row_updated_by_user_id">Initial value of the row_updated_by_user_id property.</param>
        public static file_repository Createfile_repository(global::System.Int64 file_repository_id, global::System.String file_name, global::System.Int32 status_flag, global::System.DateTime row_created, global::System.DateTime row_updated, global::System.String row_created_by_user_id, global::System.String row_updated_by_user_id)
        {
            file_repository file_repository = new file_repository();
            file_repository.file_repository_id = file_repository_id;
            file_repository.file_name = file_name;
            file_repository.status_flag = status_flag;
            file_repository.row_created = row_created;
            file_repository.row_updated = row_updated;
            file_repository.row_created_by_user_id = row_created_by_user_id;
            file_repository.row_updated_by_user_id = row_updated_by_user_id;
            return file_repository;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 file_repository_id
        {
            get
            {
                return _file_repository_id;
            }
            set
            {
                if (_file_repository_id != value)
                {
                    Onfile_repository_idChanging(value);
                    ReportPropertyChanging("file_repository_id");
                    _file_repository_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("file_repository_id");
                    Onfile_repository_idChanged();
                }
            }
        }
        private global::System.Int64 _file_repository_id;
        partial void Onfile_repository_idChanging(global::System.Int64 value);
        partial void Onfile_repository_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String file_name
        {
            get
            {
                return _file_name;
            }
            set
            {
                Onfile_nameChanging(value);
                ReportPropertyChanging("file_name");
                _file_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("file_name");
                Onfile_nameChanged();
            }
        }
        private global::System.String _file_name;
        partial void Onfile_nameChanging(global::System.String value);
        partial void Onfile_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] file_blob
        {
            get
            {
                return StructuralObject.GetValidValue(_file_blob);
            }
            set
            {
                Onfile_blobChanging(value);
                ReportPropertyChanging("file_blob");
                _file_blob = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("file_blob");
                Onfile_blobChanged();
            }
        }
        private global::System.Byte[] _file_blob;
        partial void Onfile_blobChanging(global::System.Byte[] value);
        partial void Onfile_blobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_flag
        {
            get
            {
                return _status_flag;
            }
            set
            {
                Onstatus_flagChanging(value);
                ReportPropertyChanging("status_flag");
                _status_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_flag");
                Onstatus_flagChanged();
            }
        }
        private global::System.Int32 _status_flag;
        partial void Onstatus_flagChanging(global::System.Int32 value);
        partial void Onstatus_flagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime row_created
        {
            get
            {
                return _row_created;
            }
            set
            {
                Onrow_createdChanging(value);
                ReportPropertyChanging("row_created");
                _row_created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("row_created");
                Onrow_createdChanged();
            }
        }
        private global::System.DateTime _row_created;
        partial void Onrow_createdChanging(global::System.DateTime value);
        partial void Onrow_createdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime row_updated
        {
            get
            {
                return _row_updated;
            }
            set
            {
                Onrow_updatedChanging(value);
                ReportPropertyChanging("row_updated");
                _row_updated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("row_updated");
                Onrow_updatedChanged();
            }
        }
        private global::System.DateTime _row_updated;
        partial void Onrow_updatedChanging(global::System.DateTime value);
        partial void Onrow_updatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String row_created_by_user_id
        {
            get
            {
                return _row_created_by_user_id;
            }
            set
            {
                Onrow_created_by_user_idChanging(value);
                ReportPropertyChanging("row_created_by_user_id");
                _row_created_by_user_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("row_created_by_user_id");
                Onrow_created_by_user_idChanged();
            }
        }
        private global::System.String _row_created_by_user_id;
        partial void Onrow_created_by_user_idChanging(global::System.String value);
        partial void Onrow_created_by_user_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String row_updated_by_user_id
        {
            get
            {
                return _row_updated_by_user_id;
            }
            set
            {
                Onrow_updated_by_user_idChanging(value);
                ReportPropertyChanging("row_updated_by_user_id");
                _row_updated_by_user_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("row_updated_by_user_id");
                Onrow_updated_by_user_idChanged();
            }
        }
        private global::System.String _row_updated_by_user_id;
        partial void Onrow_updated_by_user_idChanging(global::System.String value);
        partial void Onrow_updated_by_user_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ctcModel", "fk_event_file_2", "event_file")]
        public EntityCollection<event_file> event_file
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<event_file>("ctcModel.fk_event_file_2", "event_file");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<event_file>("ctcModel.fk_event_file_2", "event_file", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
