--select count(*) from (select distinct t.ctc_id
--from ctc.ctc_master t, ctc.it_event_attend_stage it
--where it.field1 = t.cps_id)t
--
--select count(*) from (select distinct field1 from ctc.it_event_attend_stage)g
--
--select count(ea.ctc_id), pro.program_name
--from ctc.events e, ctc.event_attendance ea, ctc.ctc_master m, ctc.event_program p, ctc.program pro
--where e.event_id = ea.event_id
--and ea.ctc_id = m.ctc_id
--and e.event_id = p.event_id
--and p.program_id = pro.program_id
--group by pro.program_name
-- 
--
--select count(*) from ctc.event_attendance where ctc_id is not null
--
--select count(*) from ctc.it_event_attend_stage


--select s.field1, m.cps_id, a.field7
--from ctc.it_event_stage a, 
--ctc.it_event_attend_stage s left outer join ctc.ctc_master m
--on s.field1 = m.cps_id
--where s.field2 = a.field1
--and m.cps_id is null
